// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.6
// source: secondfloor/contentagnostic/v2/playback_trait.proto

package contentagnosticpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format int32

const (
	Format_OGG_VORBIS_96                 Format = 0
	Format_OGG_VORBIS_160                Format = 1
	Format_OGG_VORBIS_320                Format = 2
	Format_MP3_256                       Format = 3
	Format_MP3_320                       Format = 4
	Format_MP3_160                       Format = 5
	Format_MP3_96                        Format = 6
	Format_MP3_160_ENC                   Format = 7
	Format_AAC_24                        Format = 8
	Format_AAC_48                        Format = 9
	Format_MP4_128                       Format = 10
	Format_MP4_256                       Format = 11
	Format_MP4_128_DUAL                  Format = 12
	Format_MP4_256_DUAL                  Format = 13
	Format_MP4_128_CBCS                  Format = 14
	Format_MP4_256_CBCS                  Format = 15
	Format_FLAC_FLAC                     Format = 16
	Format_MP4_FLAC                      Format = 17
	Format_XHE_AAC_24                    Format = 18
	Format_XHE_AAC_16                    Format = 19
	Format_XHE_AAC_12                    Format = 20
	Format_HE_AAC_64                     Format = 21
	Format_FLAC_FLAC_24BIT               Format = 22
	Format_MP4_FLAC_24BIT                Format = 23
	Format_MP4_128_CLEAR                 Format = 24
	Format_MP4_256_CLEAR                 Format = 25
	Format_WAV_PCM_UNENCRYPTED           Format = 26
	Format_OGG_VORBIS_160000_UNENCRYPTED Format = 27
	Format_MP4_HE_AAC_V1_64              Format = 28
	Format_MP4_HE_AAC_V1_96              Format = 29
	Format_MP3_32_MONO                   Format = 30
	Format_MP3_40_MONO                   Format = 31
	Format_MP3_48_MONO                   Format = 32
	Format_MP3_56_MONO                   Format = 33
	Format_MP3_64_MONO                   Format = 34
	Format_MP3_80_MONO                   Format = 35
	Format_MP3_96_MONO                   Format = 36
	Format_MP3_112_MONO                  Format = 37
	Format_MP3_128_MONO                  Format = 38
	Format_MP3_160_MONO                  Format = 39
	Format_MP3_192_MONO                  Format = 40
	Format_MP3_224_MONO                  Format = 41
	Format_MP3_256_MONO                  Format = 42
	Format_MP3_320_MONO                  Format = 43
	Format_MP3_32                        Format = 44
	Format_MP3_40                        Format = 45
	Format_MP3_48                        Format = 46
	Format_MP3_56                        Format = 47
	Format_MP3_64                        Format = 48
	Format_MP3_80                        Format = 49
	Format_MP3_112                       Format = 50
	Format_MP3_128                       Format = 51
	Format_MP3_192                       Format = 52
	Format_MP3_224                       Format = 53
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0:  "OGG_VORBIS_96",
		1:  "OGG_VORBIS_160",
		2:  "OGG_VORBIS_320",
		3:  "MP3_256",
		4:  "MP3_320",
		5:  "MP3_160",
		6:  "MP3_96",
		7:  "MP3_160_ENC",
		8:  "AAC_24",
		9:  "AAC_48",
		10: "MP4_128",
		11: "MP4_256",
		12: "MP4_128_DUAL",
		13: "MP4_256_DUAL",
		14: "MP4_128_CBCS",
		15: "MP4_256_CBCS",
		16: "FLAC_FLAC",
		17: "MP4_FLAC",
		18: "XHE_AAC_24",
		19: "XHE_AAC_16",
		20: "XHE_AAC_12",
		21: "HE_AAC_64",
		22: "FLAC_FLAC_24BIT",
		23: "MP4_FLAC_24BIT",
		24: "MP4_128_CLEAR",
		25: "MP4_256_CLEAR",
		26: "WAV_PCM_UNENCRYPTED",
		27: "OGG_VORBIS_160000_UNENCRYPTED",
		28: "MP4_HE_AAC_V1_64",
		29: "MP4_HE_AAC_V1_96",
		30: "MP3_32_MONO",
		31: "MP3_40_MONO",
		32: "MP3_48_MONO",
		33: "MP3_56_MONO",
		34: "MP3_64_MONO",
		35: "MP3_80_MONO",
		36: "MP3_96_MONO",
		37: "MP3_112_MONO",
		38: "MP3_128_MONO",
		39: "MP3_160_MONO",
		40: "MP3_192_MONO",
		41: "MP3_224_MONO",
		42: "MP3_256_MONO",
		43: "MP3_320_MONO",
		44: "MP3_32",
		45: "MP3_40",
		46: "MP3_48",
		47: "MP3_56",
		48: "MP3_64",
		49: "MP3_80",
		50: "MP3_112",
		51: "MP3_128",
		52: "MP3_192",
		53: "MP3_224",
	}
	Format_value = map[string]int32{
		"OGG_VORBIS_96":                 0,
		"OGG_VORBIS_160":                1,
		"OGG_VORBIS_320":                2,
		"MP3_256":                       3,
		"MP3_320":                       4,
		"MP3_160":                       5,
		"MP3_96":                        6,
		"MP3_160_ENC":                   7,
		"AAC_24":                        8,
		"AAC_48":                        9,
		"MP4_128":                       10,
		"MP4_256":                       11,
		"MP4_128_DUAL":                  12,
		"MP4_256_DUAL":                  13,
		"MP4_128_CBCS":                  14,
		"MP4_256_CBCS":                  15,
		"FLAC_FLAC":                     16,
		"MP4_FLAC":                      17,
		"XHE_AAC_24":                    18,
		"XHE_AAC_16":                    19,
		"XHE_AAC_12":                    20,
		"HE_AAC_64":                     21,
		"FLAC_FLAC_24BIT":               22,
		"MP4_FLAC_24BIT":                23,
		"MP4_128_CLEAR":                 24,
		"MP4_256_CLEAR":                 25,
		"WAV_PCM_UNENCRYPTED":           26,
		"OGG_VORBIS_160000_UNENCRYPTED": 27,
		"MP4_HE_AAC_V1_64":              28,
		"MP4_HE_AAC_V1_96":              29,
		"MP3_32_MONO":                   30,
		"MP3_40_MONO":                   31,
		"MP3_48_MONO":                   32,
		"MP3_56_MONO":                   33,
		"MP3_64_MONO":                   34,
		"MP3_80_MONO":                   35,
		"MP3_96_MONO":                   36,
		"MP3_112_MONO":                  37,
		"MP3_128_MONO":                  38,
		"MP3_160_MONO":                  39,
		"MP3_192_MONO":                  40,
		"MP3_224_MONO":                  41,
		"MP3_256_MONO":                  42,
		"MP3_320_MONO":                  43,
		"MP3_32":                        44,
		"MP3_40":                        45,
		"MP3_48":                        46,
		"MP3_56":                        47,
		"MP3_64":                        48,
		"MP3_80":                        49,
		"MP3_112":                       50,
		"MP3_128":                       51,
		"MP3_192":                       52,
		"MP3_224":                       53,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_secondfloor_contentagnostic_v2_playback_trait_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Format) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Format(num)
	return nil
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{0}
}

type AudioMediaFormat int32

const (
	AudioMediaFormat_AUDIO_MEDIA_FORMAT_UNKNOWN AudioMediaFormat = 0
)

// Enum value maps for AudioMediaFormat.
var (
	AudioMediaFormat_name = map[int32]string{
		0: "AUDIO_MEDIA_FORMAT_UNKNOWN",
	}
	AudioMediaFormat_value = map[string]int32{
		"AUDIO_MEDIA_FORMAT_UNKNOWN": 0,
	}
)

func (x AudioMediaFormat) Enum() *AudioMediaFormat {
	p := new(AudioMediaFormat)
	*p = x
	return p
}

func (x AudioMediaFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioMediaFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_enumTypes[1].Descriptor()
}

func (AudioMediaFormat) Type() protoreflect.EnumType {
	return &file_secondfloor_contentagnostic_v2_playback_trait_proto_enumTypes[1]
}

func (x AudioMediaFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AudioMediaFormat) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AudioMediaFormat(num)
	return nil
}

// Deprecated: Use AudioMediaFormat.Descriptor instead.
func (AudioMediaFormat) EnumDescriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{1}
}

type VideoMediaFormat int32

const (
	VideoMediaFormat_VIDEO_MEDIA_FORMAT_UNKNOWN VideoMediaFormat = 0
)

// Enum value maps for VideoMediaFormat.
var (
	VideoMediaFormat_name = map[int32]string{
		0: "VIDEO_MEDIA_FORMAT_UNKNOWN",
	}
	VideoMediaFormat_value = map[string]int32{
		"VIDEO_MEDIA_FORMAT_UNKNOWN": 0,
	}
)

func (x VideoMediaFormat) Enum() *VideoMediaFormat {
	p := new(VideoMediaFormat)
	*p = x
	return p
}

func (x VideoMediaFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoMediaFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_enumTypes[2].Descriptor()
}

func (VideoMediaFormat) Type() protoreflect.EnumType {
	return &file_secondfloor_contentagnostic_v2_playback_trait_proto_enumTypes[2]
}

func (x VideoMediaFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *VideoMediaFormat) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = VideoMediaFormat(num)
	return nil
}

// Deprecated: Use VideoMediaFormat.Descriptor instead.
func (VideoMediaFormat) EnumDescriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{2}
}

type PlaybackTrait struct {
	state          protoimpl.MessageState         `protogen:"open.v1"`
	Audio          []*PlaybackTrait_AudioMapEntry `protobuf:"bytes,1,rep,name=audio" json:"audio,omitempty"`
	Video          []*PlaybackTrait_VideoMapEntry `protobuf:"bytes,2,rep,name=video" json:"video,omitempty"`
	TransitionMaps *TransitionMaps                `protobuf:"bytes,3,opt,name=transition_maps,json=transitionMaps" json:"transition_maps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlaybackTrait) Reset() {
	*x = PlaybackTrait{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackTrait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackTrait) ProtoMessage() {}

func (x *PlaybackTrait) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackTrait.ProtoReflect.Descriptor instead.
func (*PlaybackTrait) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{0}
}

func (x *PlaybackTrait) GetAudio() []*PlaybackTrait_AudioMapEntry {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *PlaybackTrait) GetVideo() []*PlaybackTrait_VideoMapEntry {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *PlaybackTrait) GetTransitionMaps() *TransitionMaps {
	if x != nil {
		return x.TransitionMaps
	}
	return nil
}

type AudioPlayback struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	PassThrough             *AudioPassThrough      `protobuf:"bytes,1,opt,name=pass_through,json=passThrough" json:"pass_through,omitempty"`
	Hosted                  *AudioHosted           `protobuf:"bytes,2,opt,name=hosted" json:"hosted,omitempty"`
	Hls                     *AudioHls              `protobuf:"bytes,5,opt,name=hls" json:"hls,omitempty"`
	ReportingUri            *string                `protobuf:"bytes,3,opt,name=reporting_uri,json=reportingUri" json:"reporting_uri,omitempty"`
	Offsets                 *PlaybackOffsets       `protobuf:"bytes,4,opt,name=offsets" json:"offsets,omitempty"`
	UriForMigrationPurposes *string                `protobuf:"bytes,6,opt,name=uri_for_migration_purposes,json=uriForMigrationPurposes" json:"uri_for_migration_purposes,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AudioPlayback) Reset() {
	*x = AudioPlayback{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioPlayback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioPlayback) ProtoMessage() {}

func (x *AudioPlayback) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioPlayback.ProtoReflect.Descriptor instead.
func (*AudioPlayback) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{1}
}

func (x *AudioPlayback) GetPassThrough() *AudioPassThrough {
	if x != nil {
		return x.PassThrough
	}
	return nil
}

func (x *AudioPlayback) GetHosted() *AudioHosted {
	if x != nil {
		return x.Hosted
	}
	return nil
}

func (x *AudioPlayback) GetHls() *AudioHls {
	if x != nil {
		return x.Hls
	}
	return nil
}

func (x *AudioPlayback) GetReportingUri() string {
	if x != nil && x.ReportingUri != nil {
		return *x.ReportingUri
	}
	return ""
}

func (x *AudioPlayback) GetOffsets() *PlaybackOffsets {
	if x != nil {
		return x.Offsets
	}
	return nil
}

func (x *AudioPlayback) GetUriForMigrationPurposes() string {
	if x != nil && x.UriForMigrationPurposes != nil {
		return *x.UriForMigrationPurposes
	}
	return ""
}

type AudioHosted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*AudioFile           `protobuf:"bytes,1,rep,name=files" json:"files,omitempty"`
	AudioId       []byte                 `protobuf:"bytes,2,opt,name=audio_id,json=audioId" json:"audio_id,omitempty"`
	FileNorm      *NormalizationParams   `protobuf:"bytes,3,opt,name=file_norm,json=fileNorm" json:"file_norm,omitempty"`
	GroupNorm     *NormalizationParams   `protobuf:"bytes,4,opt,name=group_norm,json=groupNorm" json:"group_norm,omitempty"`
	Offsets       *PlaybackOffsets       `protobuf:"bytes,5,opt,name=offsets" json:"offsets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioHosted) Reset() {
	*x = AudioHosted{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioHosted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioHosted) ProtoMessage() {}

func (x *AudioHosted) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioHosted.ProtoReflect.Descriptor instead.
func (*AudioHosted) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{2}
}

func (x *AudioHosted) GetFiles() []*AudioFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *AudioHosted) GetAudioId() []byte {
	if x != nil {
		return x.AudioId
	}
	return nil
}

func (x *AudioHosted) GetFileNorm() *NormalizationParams {
	if x != nil {
		return x.FileNorm
	}
	return nil
}

func (x *AudioHosted) GetGroupNorm() *NormalizationParams {
	if x != nil {
		return x.GroupNorm
	}
	return nil
}

func (x *AudioHosted) GetOffsets() *PlaybackOffsets {
	if x != nil {
		return x.Offsets
	}
	return nil
}

type AudioFile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileId         []byte                 `protobuf:"bytes,1,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
	Format         *Format                `protobuf:"varint,2,opt,name=format,enum=secondfloor.contentagnostic.v2.Format" json:"format,omitempty"`
	AverageBitrate *int32                 `protobuf:"varint,3,opt,name=average_bitrate,json=averageBitrate" json:"average_bitrate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AudioFile) Reset() {
	*x = AudioFile{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFile) ProtoMessage() {}

func (x *AudioFile) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFile.ProtoReflect.Descriptor instead.
func (*AudioFile) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{3}
}

func (x *AudioFile) GetFileId() []byte {
	if x != nil {
		return x.FileId
	}
	return nil
}

func (x *AudioFile) GetFormat() Format {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return Format_OGG_VORBIS_96
}

func (x *AudioFile) GetAverageBitrate() int32 {
	if x != nil && x.AverageBitrate != nil {
		return *x.AverageBitrate
	}
	return 0
}

type AudioPassThrough struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlatFile      *FlatFile              `protobuf:"bytes,1,opt,name=flat_file,json=flatFile" json:"flat_file,omitempty"`
	Fallback      *AudioHosted           `protobuf:"bytes,3,opt,name=fallback" json:"fallback,omitempty"`
	AdDetection   *AdDetection           `protobuf:"bytes,4,opt,name=ad_detection,json=adDetection" json:"ad_detection,omitempty"`
	Offsets       *PlaybackOffsets       `protobuf:"bytes,5,opt,name=offsets" json:"offsets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioPassThrough) Reset() {
	*x = AudioPassThrough{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioPassThrough) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioPassThrough) ProtoMessage() {}

func (x *AudioPassThrough) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioPassThrough.ProtoReflect.Descriptor instead.
func (*AudioPassThrough) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{4}
}

func (x *AudioPassThrough) GetFlatFile() *FlatFile {
	if x != nil {
		return x.FlatFile
	}
	return nil
}

func (x *AudioPassThrough) GetFallback() *AudioHosted {
	if x != nil {
		return x.Fallback
	}
	return nil
}

func (x *AudioPassThrough) GetAdDetection() *AdDetection {
	if x != nil {
		return x.AdDetection
	}
	return nil
}

func (x *AudioPassThrough) GetOffsets() *PlaybackOffsets {
	if x != nil {
		return x.Offsets
	}
	return nil
}

type AudioHls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlatFile      *FlatFile              `protobuf:"bytes,1,opt,name=flat_file,json=flatFile" json:"flat_file,omitempty"`
	Offsets       *PlaybackOffsets       `protobuf:"bytes,2,opt,name=offsets" json:"offsets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioHls) Reset() {
	*x = AudioHls{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioHls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioHls) ProtoMessage() {}

func (x *AudioHls) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioHls.ProtoReflect.Descriptor instead.
func (*AudioHls) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{5}
}

func (x *AudioHls) GetFlatFile() *FlatFile {
	if x != nil {
		return x.FlatFile
	}
	return nil
}

func (x *AudioHls) GetOffsets() *PlaybackOffsets {
	if x != nil {
		return x.Offsets
	}
	return nil
}

type VideoPlayback struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Hosted                  *VideoHosted           `protobuf:"bytes,1,opt,name=hosted" json:"hosted,omitempty"`
	ReportingUri            *string                `protobuf:"bytes,2,opt,name=reporting_uri,json=reportingUri" json:"reporting_uri,omitempty"`
	Offsets                 *PlaybackOffsets       `protobuf:"bytes,3,opt,name=offsets" json:"offsets,omitempty"`
	UriForMigrationPurposes *string                `protobuf:"bytes,4,opt,name=uri_for_migration_purposes,json=uriForMigrationPurposes" json:"uri_for_migration_purposes,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *VideoPlayback) Reset() {
	*x = VideoPlayback{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoPlayback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoPlayback) ProtoMessage() {}

func (x *VideoPlayback) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoPlayback.ProtoReflect.Descriptor instead.
func (*VideoPlayback) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{6}
}

func (x *VideoPlayback) GetHosted() *VideoHosted {
	if x != nil {
		return x.Hosted
	}
	return nil
}

func (x *VideoPlayback) GetReportingUri() string {
	if x != nil && x.ReportingUri != nil {
		return *x.ReportingUri
	}
	return ""
}

func (x *VideoPlayback) GetOffsets() *PlaybackOffsets {
	if x != nil {
		return x.Offsets
	}
	return nil
}

func (x *VideoPlayback) GetUriForMigrationPurposes() string {
	if x != nil && x.UriForMigrationPurposes != nil {
		return *x.UriForMigrationPurposes
	}
	return ""
}

type VideoHosted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       []byte                 `protobuf:"bytes,1,opt,name=video_id,json=videoId" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoHosted) Reset() {
	*x = VideoHosted{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoHosted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoHosted) ProtoMessage() {}

func (x *VideoHosted) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoHosted.ProtoReflect.Descriptor instead.
func (*VideoHosted) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{7}
}

func (x *VideoHosted) GetVideoId() []byte {
	if x != nil {
		return x.VideoId
	}
	return nil
}

type AdDetection struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FallbackOffsets *PlaybackOffsets       `protobuf:"bytes,1,opt,name=fallback_offsets,json=fallbackOffsets" json:"fallback_offsets,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdDetection) Reset() {
	*x = AdDetection{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdDetection) ProtoMessage() {}

func (x *AdDetection) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdDetection.ProtoReflect.Descriptor instead.
func (*AdDetection) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{8}
}

func (x *AdDetection) GetFallbackOffsets() *PlaybackOffsets {
	if x != nil {
		return x.FallbackOffsets
	}
	return nil
}

type NormalizationParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoudnessDb    *float32               `protobuf:"fixed32,1,opt,name=loudness_db,json=loudnessDb" json:"loudness_db,omitempty"`
	TruePeakDb    *float32               `protobuf:"fixed32,2,opt,name=true_peak_db,json=truePeakDb" json:"true_peak_db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizationParams) Reset() {
	*x = NormalizationParams{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizationParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizationParams) ProtoMessage() {}

func (x *NormalizationParams) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizationParams.ProtoReflect.Descriptor instead.
func (*NormalizationParams) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{9}
}

func (x *NormalizationParams) GetLoudnessDb() float32 {
	if x != nil && x.LoudnessDb != nil {
		return *x.LoudnessDb
	}
	return 0
}

func (x *NormalizationParams) GetTruePeakDb() float32 {
	if x != nil && x.TruePeakDb != nil {
		return *x.TruePeakDb
	}
	return 0
}

type PlaybackOffsets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *Duration              `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	End           *Duration              `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackOffsets) Reset() {
	*x = PlaybackOffsets{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackOffsets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackOffsets) ProtoMessage() {}

func (x *PlaybackOffsets) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackOffsets.ProtoReflect.Descriptor instead.
func (*PlaybackOffsets) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{10}
}

func (x *PlaybackOffsets) GetStart() *Duration {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *PlaybackOffsets) GetEnd() *Duration {
	if x != nil {
		return x.End
	}
	return nil
}

type FlatFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatFile) Reset() {
	*x = FlatFile{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatFile) ProtoMessage() {}

func (x *FlatFile) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatFile.ProtoReflect.Descriptor instead.
func (*FlatFile) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{11}
}

type TransitionMaps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionMaps) Reset() {
	*x = TransitionMaps{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionMaps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionMaps) ProtoMessage() {}

func (x *TransitionMaps) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionMaps.ProtoReflect.Descriptor instead.
func (*TransitionMaps) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{12}
}

type Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       *int64                 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	Nanos         *int32                 `protobuf:"varint,2,opt,name=nanos" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{13}
}

func (x *Duration) GetSeconds() int64 {
	if x != nil && x.Seconds != nil {
		return *x.Seconds
	}
	return 0
}

func (x *Duration) GetNanos() int32 {
	if x != nil && x.Nanos != nil {
		return *x.Nanos
	}
	return 0
}

type PlaybackTrait_AudioMapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *AudioMediaFormat      `protobuf:"varint,1,opt,name=key,enum=secondfloor.contentagnostic.v2.AudioMediaFormat" json:"key,omitempty"`
	Value         *AudioPlayback         `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackTrait_AudioMapEntry) Reset() {
	*x = PlaybackTrait_AudioMapEntry{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackTrait_AudioMapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackTrait_AudioMapEntry) ProtoMessage() {}

func (x *PlaybackTrait_AudioMapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackTrait_AudioMapEntry.ProtoReflect.Descriptor instead.
func (*PlaybackTrait_AudioMapEntry) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PlaybackTrait_AudioMapEntry) GetKey() AudioMediaFormat {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return AudioMediaFormat_AUDIO_MEDIA_FORMAT_UNKNOWN
}

func (x *PlaybackTrait_AudioMapEntry) GetValue() *AudioPlayback {
	if x != nil {
		return x.Value
	}
	return nil
}

type PlaybackTrait_VideoMapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *VideoMediaFormat      `protobuf:"varint,1,opt,name=key,enum=secondfloor.contentagnostic.v2.VideoMediaFormat" json:"key,omitempty"`
	Value         *VideoPlayback         `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackTrait_VideoMapEntry) Reset() {
	*x = PlaybackTrait_VideoMapEntry{}
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackTrait_VideoMapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackTrait_VideoMapEntry) ProtoMessage() {}

func (x *PlaybackTrait_VideoMapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackTrait_VideoMapEntry.ProtoReflect.Descriptor instead.
func (*PlaybackTrait_VideoMapEntry) Descriptor() ([]byte, []int) {
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PlaybackTrait_VideoMapEntry) GetKey() VideoMediaFormat {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return VideoMediaFormat_VIDEO_MEDIA_FORMAT_UNKNOWN
}

func (x *PlaybackTrait_VideoMapEntry) GetValue() *VideoPlayback {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_secondfloor_contentagnostic_v2_playback_trait_proto protoreflect.FileDescriptor

const file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDesc = "" +
	"\n" +
	"3secondfloor/contentagnostic/v2/playback_trait.proto\x12\x1esecondfloor.contentagnostic.v2\"\xc4\x04\n" +
	"\rPlaybackTrait\x12Q\n" +
	"\x05audio\x18\x01 \x03(\v2;.secondfloor.contentagnostic.v2.PlaybackTrait.AudioMapEntryR\x05audio\x12Q\n" +
	"\x05video\x18\x02 \x03(\v2;.secondfloor.contentagnostic.v2.PlaybackTrait.VideoMapEntryR\x05video\x12W\n" +
	"\x0ftransition_maps\x18\x03 \x01(\v2..secondfloor.contentagnostic.v2.TransitionMapsR\x0etransitionMaps\x1a\x98\x01\n" +
	"\rAudioMapEntry\x12B\n" +
	"\x03key\x18\x01 \x01(\x0e20.secondfloor.contentagnostic.v2.AudioMediaFormatR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.secondfloor.contentagnostic.v2.AudioPlaybackR\x05value\x1a\x98\x01\n" +
	"\rVideoMapEntry\x12B\n" +
	"\x03key\x18\x01 \x01(\x0e20.secondfloor.contentagnostic.v2.VideoMediaFormatR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.secondfloor.contentagnostic.v2.VideoPlaybackR\x05value\"\x92\x03\n" +
	"\rAudioPlayback\x12S\n" +
	"\fpass_through\x18\x01 \x01(\v20.secondfloor.contentagnostic.v2.AudioPassThroughR\vpassThrough\x12C\n" +
	"\x06hosted\x18\x02 \x01(\v2+.secondfloor.contentagnostic.v2.AudioHostedR\x06hosted\x12:\n" +
	"\x03hls\x18\x05 \x01(\v2(.secondfloor.contentagnostic.v2.AudioHlsR\x03hls\x12#\n" +
	"\rreporting_uri\x18\x03 \x01(\tR\freportingUri\x12I\n" +
	"\aoffsets\x18\x04 \x01(\v2/.secondfloor.contentagnostic.v2.PlaybackOffsetsR\aoffsets\x12;\n" +
	"\x1auri_for_migration_purposes\x18\x06 \x01(\tR\x17uriForMigrationPurposes\"\xda\x02\n" +
	"\vAudioHosted\x12?\n" +
	"\x05files\x18\x01 \x03(\v2).secondfloor.contentagnostic.v2.AudioFileR\x05files\x12\x19\n" +
	"\baudio_id\x18\x02 \x01(\fR\aaudioId\x12P\n" +
	"\tfile_norm\x18\x03 \x01(\v23.secondfloor.contentagnostic.v2.NormalizationParamsR\bfileNorm\x12R\n" +
	"\n" +
	"group_norm\x18\x04 \x01(\v23.secondfloor.contentagnostic.v2.NormalizationParamsR\tgroupNorm\x12I\n" +
	"\aoffsets\x18\x05 \x01(\v2/.secondfloor.contentagnostic.v2.PlaybackOffsetsR\aoffsets\"\x8d\x01\n" +
	"\tAudioFile\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\fR\x06fileId\x12>\n" +
	"\x06format\x18\x02 \x01(\x0e2&.secondfloor.contentagnostic.v2.FormatR\x06format\x12'\n" +
	"\x0faverage_bitrate\x18\x03 \x01(\x05R\x0eaverageBitrate\"\xbd\x02\n" +
	"\x10AudioPassThrough\x12E\n" +
	"\tflat_file\x18\x01 \x01(\v2(.secondfloor.contentagnostic.v2.FlatFileR\bflatFile\x12G\n" +
	"\bfallback\x18\x03 \x01(\v2+.secondfloor.contentagnostic.v2.AudioHostedR\bfallback\x12N\n" +
	"\fad_detection\x18\x04 \x01(\v2+.secondfloor.contentagnostic.v2.AdDetectionR\vadDetection\x12I\n" +
	"\aoffsets\x18\x05 \x01(\v2/.secondfloor.contentagnostic.v2.PlaybackOffsetsR\aoffsets\"\x9c\x01\n" +
	"\bAudioHls\x12E\n" +
	"\tflat_file\x18\x01 \x01(\v2(.secondfloor.contentagnostic.v2.FlatFileR\bflatFile\x12I\n" +
	"\aoffsets\x18\x02 \x01(\v2/.secondfloor.contentagnostic.v2.PlaybackOffsetsR\aoffsets\"\x81\x02\n" +
	"\rVideoPlayback\x12C\n" +
	"\x06hosted\x18\x01 \x01(\v2+.secondfloor.contentagnostic.v2.VideoHostedR\x06hosted\x12#\n" +
	"\rreporting_uri\x18\x02 \x01(\tR\freportingUri\x12I\n" +
	"\aoffsets\x18\x03 \x01(\v2/.secondfloor.contentagnostic.v2.PlaybackOffsetsR\aoffsets\x12;\n" +
	"\x1auri_for_migration_purposes\x18\x04 \x01(\tR\x17uriForMigrationPurposes\"(\n" +
	"\vVideoHosted\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\fR\avideoId\"i\n" +
	"\vAdDetection\x12Z\n" +
	"\x10fallback_offsets\x18\x01 \x01(\v2/.secondfloor.contentagnostic.v2.PlaybackOffsetsR\x0ffallbackOffsets\"X\n" +
	"\x13NormalizationParams\x12\x1f\n" +
	"\vloudness_db\x18\x01 \x01(\x02R\n" +
	"loudnessDb\x12 \n" +
	"\ftrue_peak_db\x18\x02 \x01(\x02R\n" +
	"truePeakDb\"\x8d\x01\n" +
	"\x0fPlaybackOffsets\x12>\n" +
	"\x05start\x18\x01 \x01(\v2(.secondfloor.contentagnostic.v2.DurationR\x05start\x12:\n" +
	"\x03end\x18\x02 \x01(\v2(.secondfloor.contentagnostic.v2.DurationR\x03end\"\n" +
	"\n" +
	"\bFlatFile\"\x10\n" +
	"\x0eTransitionMaps\":\n" +
	"\bDuration\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos*\x85\a\n" +
	"\x06Format\x12\x11\n" +
	"\rOGG_VORBIS_96\x10\x00\x12\x12\n" +
	"\x0eOGG_VORBIS_160\x10\x01\x12\x12\n" +
	"\x0eOGG_VORBIS_320\x10\x02\x12\v\n" +
	"\aMP3_256\x10\x03\x12\v\n" +
	"\aMP3_320\x10\x04\x12\v\n" +
	"\aMP3_160\x10\x05\x12\n" +
	"\n" +
	"\x06MP3_96\x10\x06\x12\x0f\n" +
	"\vMP3_160_ENC\x10\a\x12\n" +
	"\n" +
	"\x06AAC_24\x10\b\x12\n" +
	"\n" +
	"\x06AAC_48\x10\t\x12\v\n" +
	"\aMP4_128\x10\n" +
	"\x12\v\n" +
	"\aMP4_256\x10\v\x12\x10\n" +
	"\fMP4_128_DUAL\x10\f\x12\x10\n" +
	"\fMP4_256_DUAL\x10\r\x12\x10\n" +
	"\fMP4_128_CBCS\x10\x0e\x12\x10\n" +
	"\fMP4_256_CBCS\x10\x0f\x12\r\n" +
	"\tFLAC_FLAC\x10\x10\x12\f\n" +
	"\bMP4_FLAC\x10\x11\x12\x0e\n" +
	"\n" +
	"XHE_AAC_24\x10\x12\x12\x0e\n" +
	"\n" +
	"XHE_AAC_16\x10\x13\x12\x0e\n" +
	"\n" +
	"XHE_AAC_12\x10\x14\x12\r\n" +
	"\tHE_AAC_64\x10\x15\x12\x13\n" +
	"\x0fFLAC_FLAC_24BIT\x10\x16\x12\x12\n" +
	"\x0eMP4_FLAC_24BIT\x10\x17\x12\x11\n" +
	"\rMP4_128_CLEAR\x10\x18\x12\x11\n" +
	"\rMP4_256_CLEAR\x10\x19\x12\x17\n" +
	"\x13WAV_PCM_UNENCRYPTED\x10\x1a\x12!\n" +
	"\x1dOGG_VORBIS_160000_UNENCRYPTED\x10\x1b\x12\x14\n" +
	"\x10MP4_HE_AAC_V1_64\x10\x1c\x12\x14\n" +
	"\x10MP4_HE_AAC_V1_96\x10\x1d\x12\x0f\n" +
	"\vMP3_32_MONO\x10\x1e\x12\x0f\n" +
	"\vMP3_40_MONO\x10\x1f\x12\x0f\n" +
	"\vMP3_48_MONO\x10 \x12\x0f\n" +
	"\vMP3_56_MONO\x10!\x12\x0f\n" +
	"\vMP3_64_MONO\x10\"\x12\x0f\n" +
	"\vMP3_80_MONO\x10#\x12\x0f\n" +
	"\vMP3_96_MONO\x10$\x12\x10\n" +
	"\fMP3_112_MONO\x10%\x12\x10\n" +
	"\fMP3_128_MONO\x10&\x12\x10\n" +
	"\fMP3_160_MONO\x10'\x12\x10\n" +
	"\fMP3_192_MONO\x10(\x12\x10\n" +
	"\fMP3_224_MONO\x10)\x12\x10\n" +
	"\fMP3_256_MONO\x10*\x12\x10\n" +
	"\fMP3_320_MONO\x10+\x12\n" +
	"\n" +
	"\x06MP3_32\x10,\x12\n" +
	"\n" +
	"\x06MP3_40\x10-\x12\n" +
	"\n" +
	"\x06MP3_48\x10.\x12\n" +
	"\n" +
	"\x06MP3_56\x10/\x12\n" +
	"\n" +
	"\x06MP3_64\x100\x12\n" +
	"\n" +
	"\x06MP3_80\x101\x12\v\n" +
	"\aMP3_112\x102\x12\v\n" +
	"\aMP3_128\x103\x12\v\n" +
	"\aMP3_192\x104\x12\v\n" +
	"\aMP3_224\x105*2\n" +
	"\x10AudioMediaFormat\x12\x1e\n" +
	"\x1aAUDIO_MEDIA_FORMAT_UNKNOWN\x10\x00*2\n" +
	"\x10VideoMediaFormat\x12\x1e\n" +
	"\x1aVIDEO_MEDIA_FORMAT_UNKNOWN\x10\x00BGZEgithub.com/DavidBuchanan314/secondfloor/secondfloor/contentagnosticpb"

var (
	file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescOnce sync.Once
	file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescData []byte
)

func file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescGZIP() []byte {
	file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescOnce.Do(func() {
		file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDesc), len(file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDesc)))
	})
	return file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDescData
}

var file_secondfloor_contentagnostic_v2_playback_trait_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_secondfloor_contentagnostic_v2_playback_trait_proto_goTypes = []any{
	(Format)(0),                         // 0: secondfloor.contentagnostic.v2.Format
	(AudioMediaFormat)(0),               // 1: secondfloor.contentagnostic.v2.AudioMediaFormat
	(VideoMediaFormat)(0),               // 2: secondfloor.contentagnostic.v2.VideoMediaFormat
	(*PlaybackTrait)(nil),               // 3: secondfloor.contentagnostic.v2.PlaybackTrait
	(*AudioPlayback)(nil),               // 4: secondfloor.contentagnostic.v2.AudioPlayback
	(*AudioHosted)(nil),                 // 5: secondfloor.contentagnostic.v2.AudioHosted
	(*AudioFile)(nil),                   // 6: secondfloor.contentagnostic.v2.AudioFile
	(*AudioPassThrough)(nil),            // 7: secondfloor.contentagnostic.v2.AudioPassThrough
	(*AudioHls)(nil),                    // 8: secondfloor.contentagnostic.v2.AudioHls
	(*VideoPlayback)(nil),               // 9: secondfloor.contentagnostic.v2.VideoPlayback
	(*VideoHosted)(nil),                 // 10: secondfloor.contentagnostic.v2.VideoHosted
	(*AdDetection)(nil),                 // 11: secondfloor.contentagnostic.v2.AdDetection
	(*NormalizationParams)(nil),         // 12: secondfloor.contentagnostic.v2.NormalizationParams
	(*PlaybackOffsets)(nil),             // 13: secondfloor.contentagnostic.v2.PlaybackOffsets
	(*FlatFile)(nil),                    // 14: secondfloor.contentagnostic.v2.FlatFile
	(*TransitionMaps)(nil),              // 15: secondfloor.contentagnostic.v2.TransitionMaps
	(*Duration)(nil),                    // 16: secondfloor.contentagnostic.v2.Duration
	(*PlaybackTrait_AudioMapEntry)(nil), // 17: secondfloor.contentagnostic.v2.PlaybackTrait.AudioMapEntry
	(*PlaybackTrait_VideoMapEntry)(nil), // 18: secondfloor.contentagnostic.v2.PlaybackTrait.VideoMapEntry
}
var file_secondfloor_contentagnostic_v2_playback_trait_proto_depIdxs = []int32{
	17, // 0: secondfloor.contentagnostic.v2.PlaybackTrait.audio:type_name -> secondfloor.contentagnostic.v2.PlaybackTrait.AudioMapEntry
	18, // 1: secondfloor.contentagnostic.v2.PlaybackTrait.video:type_name -> secondfloor.contentagnostic.v2.PlaybackTrait.VideoMapEntry
	15, // 2: secondfloor.contentagnostic.v2.PlaybackTrait.transition_maps:type_name -> secondfloor.contentagnostic.v2.TransitionMaps
	7,  // 3: secondfloor.contentagnostic.v2.AudioPlayback.pass_through:type_name -> secondfloor.contentagnostic.v2.AudioPassThrough
	5,  // 4: secondfloor.contentagnostic.v2.AudioPlayback.hosted:type_name -> secondfloor.contentagnostic.v2.AudioHosted
	8,  // 5: secondfloor.contentagnostic.v2.AudioPlayback.hls:type_name -> secondfloor.contentagnostic.v2.AudioHls
	13, // 6: secondfloor.contentagnostic.v2.AudioPlayback.offsets:type_name -> secondfloor.contentagnostic.v2.PlaybackOffsets
	6,  // 7: secondfloor.contentagnostic.v2.AudioHosted.files:type_name -> secondfloor.contentagnostic.v2.AudioFile
	12, // 8: secondfloor.contentagnostic.v2.AudioHosted.file_norm:type_name -> secondfloor.contentagnostic.v2.NormalizationParams
	12, // 9: secondfloor.contentagnostic.v2.AudioHosted.group_norm:type_name -> secondfloor.contentagnostic.v2.NormalizationParams
	13, // 10: secondfloor.contentagnostic.v2.AudioHosted.offsets:type_name -> secondfloor.contentagnostic.v2.PlaybackOffsets
	0,  // 11: secondfloor.contentagnostic.v2.AudioFile.format:type_name -> secondfloor.contentagnostic.v2.Format
	14, // 12: secondfloor.contentagnostic.v2.AudioPassThrough.flat_file:type_name -> secondfloor.contentagnostic.v2.FlatFile
	5,  // 13: secondfloor.contentagnostic.v2.AudioPassThrough.fallback:type_name -> secondfloor.contentagnostic.v2.AudioHosted
	11, // 14: secondfloor.contentagnostic.v2.AudioPassThrough.ad_detection:type_name -> secondfloor.contentagnostic.v2.AdDetection
	13, // 15: secondfloor.contentagnostic.v2.AudioPassThrough.offsets:type_name -> secondfloor.contentagnostic.v2.PlaybackOffsets
	14, // 16: secondfloor.contentagnostic.v2.AudioHls.flat_file:type_name -> secondfloor.contentagnostic.v2.FlatFile
	13, // 17: secondfloor.contentagnostic.v2.AudioHls.offsets:type_name -> secondfloor.contentagnostic.v2.PlaybackOffsets
	10, // 18: secondfloor.contentagnostic.v2.VideoPlayback.hosted:type_name -> secondfloor.contentagnostic.v2.VideoHosted
	13, // 19: secondfloor.contentagnostic.v2.VideoPlayback.offsets:type_name -> secondfloor.contentagnostic.v2.PlaybackOffsets
	13, // 20: secondfloor.contentagnostic.v2.AdDetection.fallback_offsets:type_name -> secondfloor.contentagnostic.v2.PlaybackOffsets
	16, // 21: secondfloor.contentagnostic.v2.PlaybackOffsets.start:type_name -> secondfloor.contentagnostic.v2.Duration
	16, // 22: secondfloor.contentagnostic.v2.PlaybackOffsets.end:type_name -> secondfloor.contentagnostic.v2.Duration
	1,  // 23: secondfloor.contentagnostic.v2.PlaybackTrait.AudioMapEntry.key:type_name -> secondfloor.contentagnostic.v2.AudioMediaFormat
	4,  // 24: secondfloor.contentagnostic.v2.PlaybackTrait.AudioMapEntry.value:type_name -> secondfloor.contentagnostic.v2.AudioPlayback
	2,  // 25: secondfloor.contentagnostic.v2.PlaybackTrait.VideoMapEntry.key:type_name -> secondfloor.contentagnostic.v2.VideoMediaFormat
	9,  // 26: secondfloor.contentagnostic.v2.PlaybackTrait.VideoMapEntry.value:type_name -> secondfloor.contentagnostic.v2.VideoPlayback
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_secondfloor_contentagnostic_v2_playback_trait_proto_init() }
func file_secondfloor_contentagnostic_v2_playback_trait_proto_init() {
	if File_secondfloor_contentagnostic_v2_playback_trait_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDesc), len(file_secondfloor_contentagnostic_v2_playback_trait_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_secondfloor_contentagnostic_v2_playback_trait_proto_goTypes,
		DependencyIndexes: file_secondfloor_contentagnostic_v2_playback_trait_proto_depIdxs,
		EnumInfos:         file_secondfloor_contentagnostic_v2_playback_trait_proto_enumTypes,
		MessageInfos:      file_secondfloor_contentagnostic_v2_playback_trait_proto_msgTypes,
	}.Build()
	File_secondfloor_contentagnostic_v2_playback_trait_proto = out.File
	file_secondfloor_contentagnostic_v2_playback_trait_proto_goTypes = nil
	file_secondfloor_contentagnostic_v2_playback_trait_proto_depIdxs = nil
}
