// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.6
// source: secondfloor/collection/collection_track_entry.proto

package collectionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectionTrackEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           *string                `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	TrackName     *string                `protobuf:"bytes,2,opt,name=track_name,json=trackName" json:"track_name,omitempty"`
	AlbumUri      *string                `protobuf:"bytes,3,opt,name=album_uri,json=albumUri" json:"album_uri,omitempty"`
	AlbumName     *string                `protobuf:"bytes,4,opt,name=album_name,json=albumName" json:"album_name,omitempty"`
	DiscNumber    *int32                 `protobuf:"varint,5,opt,name=disc_number,json=discNumber" json:"disc_number,omitempty"`
	TrackNumber   *int32                 `protobuf:"varint,6,opt,name=track_number,json=trackNumber" json:"track_number,omitempty"`
	ArtistUri     *string                `protobuf:"bytes,7,opt,name=artist_uri,json=artistUri" json:"artist_uri,omitempty"`
	ArtistName    []string               `protobuf:"bytes,8,rep,name=artist_name,json=artistName" json:"artist_name,omitempty"`
	AddTime       *int64                 `protobuf:"varint,9,opt,name=add_time,json=addTime" json:"add_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionTrackEntry) Reset() {
	*x = CollectionTrackEntry{}
	mi := &file_secondfloor_collection_collection_track_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionTrackEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionTrackEntry) ProtoMessage() {}

func (x *CollectionTrackEntry) ProtoReflect() protoreflect.Message {
	mi := &file_secondfloor_collection_collection_track_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionTrackEntry.ProtoReflect.Descriptor instead.
func (*CollectionTrackEntry) Descriptor() ([]byte, []int) {
	return file_secondfloor_collection_collection_track_entry_proto_rawDescGZIP(), []int{0}
}

func (x *CollectionTrackEntry) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

func (x *CollectionTrackEntry) GetTrackName() string {
	if x != nil && x.TrackName != nil {
		return *x.TrackName
	}
	return ""
}

func (x *CollectionTrackEntry) GetAlbumUri() string {
	if x != nil && x.AlbumUri != nil {
		return *x.AlbumUri
	}
	return ""
}

func (x *CollectionTrackEntry) GetAlbumName() string {
	if x != nil && x.AlbumName != nil {
		return *x.AlbumName
	}
	return ""
}

func (x *CollectionTrackEntry) GetDiscNumber() int32 {
	if x != nil && x.DiscNumber != nil {
		return *x.DiscNumber
	}
	return 0
}

func (x *CollectionTrackEntry) GetTrackNumber() int32 {
	if x != nil && x.TrackNumber != nil {
		return *x.TrackNumber
	}
	return 0
}

func (x *CollectionTrackEntry) GetArtistUri() string {
	if x != nil && x.ArtistUri != nil {
		return *x.ArtistUri
	}
	return ""
}

func (x *CollectionTrackEntry) GetArtistName() []string {
	if x != nil {
		return x.ArtistName
	}
	return nil
}

func (x *CollectionTrackEntry) GetAddTime() int64 {
	if x != nil && x.AddTime != nil {
		return *x.AddTime
	}
	return 0
}

var File_secondfloor_collection_collection_track_entry_proto protoreflect.FileDescriptor

const file_secondfloor_collection_collection_track_entry_proto_rawDesc = "" +
	"\n" +
	"3secondfloor/collection/collection_track_entry.proto\x12\x1csecondfloor.collection.proto\"\xa2\x02\n" +
	"\x14CollectionTrackEntry\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1d\n" +
	"\n" +
	"track_name\x18\x02 \x01(\tR\ttrackName\x12\x1b\n" +
	"\talbum_uri\x18\x03 \x01(\tR\balbumUri\x12\x1d\n" +
	"\n" +
	"album_name\x18\x04 \x01(\tR\talbumName\x12\x1f\n" +
	"\vdisc_number\x18\x05 \x01(\x05R\n" +
	"discNumber\x12!\n" +
	"\ftrack_number\x18\x06 \x01(\x05R\vtrackNumber\x12\x1d\n" +
	"\n" +
	"artist_uri\x18\a \x01(\tR\tartistUri\x12\x1f\n" +
	"\vartist_name\x18\b \x03(\tR\n" +
	"artistName\x12\x19\n" +
	"\badd_time\x18\t \x01(\x03R\aaddTimeBBZ@github.com/DavidBuchanan314/secondfloor/secondfloor/collectionpb"

var (
	file_secondfloor_collection_collection_track_entry_proto_rawDescOnce sync.Once
	file_secondfloor_collection_collection_track_entry_proto_rawDescData []byte
)

func file_secondfloor_collection_collection_track_entry_proto_rawDescGZIP() []byte {
	file_secondfloor_collection_collection_track_entry_proto_rawDescOnce.Do(func() {
		file_secondfloor_collection_collection_track_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secondfloor_collection_collection_track_entry_proto_rawDesc), len(file_secondfloor_collection_collection_track_entry_proto_rawDesc)))
	})
	return file_secondfloor_collection_collection_track_entry_proto_rawDescData
}

var file_secondfloor_collection_collection_track_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_secondfloor_collection_collection_track_entry_proto_goTypes = []any{
	(*CollectionTrackEntry)(nil), // 0: secondfloor.collection.proto.CollectionTrackEntry
}
var file_secondfloor_collection_collection_track_entry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_secondfloor_collection_collection_track_entry_proto_init() }
func file_secondfloor_collection_collection_track_entry_proto_init() {
	if File_secondfloor_collection_collection_track_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secondfloor_collection_collection_track_entry_proto_rawDesc), len(file_secondfloor_collection_collection_track_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_secondfloor_collection_collection_track_entry_proto_goTypes,
		DependencyIndexes: file_secondfloor_collection_collection_track_entry_proto_depIdxs,
		MessageInfos:      file_secondfloor_collection_collection_track_entry_proto_msgTypes,
	}.Build()
	File_secondfloor_collection_collection_track_entry_proto = out.File
	file_secondfloor_collection_collection_track_entry_proto_goTypes = nil
	file_secondfloor_collection_collection_track_entry_proto_depIdxs = nil
}
